### ISSUE TITLE
Wood block relevant tool

### ISSUE THREAD

**Issue by Koelacanth** [uItimatech/BountifulBlocks#1]
The added wood blocks all have a relevant tool of pickaxe (have "#minecraft:mineable/pickaxe"), with slab and stair blocks having both pickaxe and axe as relevant tools.

![Dark Oak Flooring debug](https://github.com/user-attachments/assets/771eb46f-0507-4212-aea4-d7acb00c9b2c)
![Dark Oak Flooring Slab debug](https://github.com/user-attachments/assets/61940119-2e61-4ece-88a4-c7170512db73)

**Comment by uItimatech** [comment]
I might have messed up during the datagen and might have missed it during testing. WIll be fixed asap, thanks for reporting.
