### ISSUE TITLE
Bamboo Blocks and Potential Additions

### ISSUE THREAD

**Issue by BioMasterZap** [uItimatech/BountifulBlocks#4]
Hello, I have been trying out v0.9.5 of the mod for Fabric 1.20.4 and noticed a bit of overlap. The mod changes the Bamboo Mosaic to Bamboo Flooring and adds Bamboo Flooring Stairs and Bamboo Flooring Slabs. But Vanilla 1.20 also adds Bamboo Mosaic Stairs and Bamboo Mosaic Slabs, which are identical to the mod's Bamboo Flooring Stairs and Bamboo Flooring Slabs. Also, the Vanilla Mosaic Slabs can be used to make Mosaic/Flooring Blocks.

Aside from that, I did notice a few "missing" Vanilla Blocks that might be a good fit for this mod. The Mod already adds Obsidian variants, but there is no Obsidian Slab/Stair/Wall for the vanilla Obsidian. And while there aren’t any modded variants, the Vanilla Quartz set lacks a Quartz Wall, Smooth Quartz Wall, and Quartz Brick Slab/Stair/Wall. Also, if you wanted to delve into glass, I noticed the other day there is no Tinted Glass Pane in Vanilla.

**Comment by uItimatech** [comment]
I'll look into the bamboo block issue. I've thought about quartz and will likely add the missing blocks soon. Tinted glass panes are also a good idea.

**Comment by uItimatech** [comment]
Duplicate blocks issue fixed in 0.9.6.
