### ISSUE TITLE
Double slabs drop one slab instead of two.

### ISSUE THREAD

**Issue by LilCubo** [uItimatech/BountifulBlocks#5]
Mentioned this in a report for 0.9.4 but it was easily missed as the majority of the issue was on crafting results. Thought I should make sure to mention it again since it didn't make it into 0.9.5. Good job though dev, you were very fast with the changes last week. Don't be in any rush to fix this, its not a big deal. 

Mining a double slab (two identical slabs place on top of one another) only drops one slab instead of the expected two.

**Comment by uItimatech** [comment]
Oh I didn't see that detail in the previous issue. Will be fixed in the next update. Thank you for reporting again.

**Comment by uItimatech** [comment]
Fixed in 0.9.6.
