### ISSUE TITLE
Missing translation key is messing with server console

### ISSUE THREAD

**Issue by suerion** [uItimatech/BountifulBlocks#7]
Hey, i had used your Mod and come here fore the issue i had found.

In your mod there are missing some translation keys, after adding your mod, it messing with the server console.

should be like this 
`Preparing spawn area: 2%`

but is this 
`[23:12:13] [Worker-Main-4/INFO]: menu.preparingSpawn`

Hope you could fix it :)

Fabric 1.21.1

**Comment by uItimatech** [comment]
Weird, that is not something I modified. Will look into it.

**Comment by uItimatech** [comment]
Wasn't able to replicate. Working without issues in 0.9.5 and 0.9.6 (to be released)

**Comment by suerion** [comment]
@uItimatech 

Fabric API has fixed the issue -> https://modrinth.com/mod/fabric-api/version/0.107.0+1.21.1

**Comment by uItimatech** [comment]
Thanks for notifying me ! 

> @uItimatech 
> 
> Fabric API has fixed the issue -> https://modrinth.com/mod/fabric-api/version/0.107.0+1.21.1
